version: '3'

services:
  db:
    image: mariadb/server:10.3
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./data/dump.sql:/docker-entrypoint-initdb.d/dump.sql
  web:
    image: php:7.2.2-apache
    container_name: php_web
    depends_on:
      - db
    ports:
      - "80:80"
    volumes:
      - ./src/:/var/www/html/